### ISSUE TITLE
Typescript compile issues

### ISSUE THREAD

**Issue by dhay** [apollographql/federation#2104]
### This bug report should include:

I'm trying to upgrade to Typescript 4.7.4 and I'm getting some compile errors in the @apollo/gateway library. 

```

node_modules/@apollo/gateway/src/datasources/RemoteGraphQLDataSource.ts:122:7 - error TS2774: This condition will always return true since this function is always defined. Did you mean to call it instead?

122       options.incomingRequestContext.overallCachePolicy?.restrict
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollo/gateway/src/schema-helper/addExtensions.ts:8:7 - error TS2698: Spread types may only be created from object types.

8       ...schema.extensions.apollo,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollo/gateway/src/schema-helper/addExtensions.ts:10:12 - error TS2571: Object is of type 'unknown'.

10         ...schema.extensions.apollo?.gateway,
              ~~~~~~~~~~~~~~~~~~~~~~~~

src/middleware/SupergraphWatcher.ts:165:42 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.

165         throw new MissingSupergraphError(err);
                                             ~~~
```

I was originally using 0.51.0, but I'm seeing the same error in the `RemoteGraphQLDataSource` when upgrading to 2.0.5.

Is there a maximum version of Typescript that is supported by @apollo/federation?

Thanks!
