### ISSUE TITLE
gateway@0.28.2: use of `@include` in query causes plan with interface to subgraphs w/o implementation  

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#801]
This may have been introduced in #671 and be a regression for what's believed to be more rare use case.  The circumstance arises when:

* A query includes the use of an `@include` directive (probably `@skip`, too)
* When a subgraph extends an entity which itself implements an interface.
* But the subgraph itself does not implement the interface.

The resulting query to the service is (now) wrapped with the interface which effectively puts the burden on the subgraph to define the interface and a `__resolveType`.

(I think this is roughly right? Just trying to capture the spirit of the regression as I understand it. Please correct me if I'm mistaken!)

**Comment by harshitkumar31** [comment]
@abernix ,
The issue seems to arise when a directive (`@include` or `@skip`) is used against an inline fragment. From a brief study of code & Changelog, I think https://github.com/apollographql/federation/commit/31a7ba605b4931e5bb62d766637ffe005bd2af95 could be the possible candidate which introduced this behaviour.

**Comment by pcmanus** [comment]
The culprit is actually #652. Opened #805 with the fix.
