### ISSUE TITLE
`@types/node-fetch` is missing in the `@apollo/gateway` dependencies

### ISSUE THREAD

**Issue by Grmiade** [apollographql/federation#2113]
Since the `2.1.0` version, the `@types/node-fetch` dependency is missing.

Regression introduced in https://github.com/apollographql/federation/pull/1970/files

This error is thrown when we try to build our project:
```
#21 12.69 ../../.yarn/__virtual__/@apollo-gateway-virtual-9de6cdc87b/0/cache/@apollo-gateway-npm-2.1.0-0009d7c27c-a763b86c26.zip/node_modules/@apollo/gateway/dist/config.d.ts:2:34 - error TS7016: Could not find a declaration file for module 'node-fetch'. '/usr/src/app/.yarn/__virtual__/node-fetch-virtual-1391f376ba/0/cache/node-fetch-npm-2.6.7-777aa2a6df-8d816ffd1e.zip/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
#21 12.69   Try `npm i --save-dev @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`
#21 12.69 
#21 12.69 2 import type { HeadersInit } from 'node-fetch';
```

**Comment by clenfest** [comment]
Strange. `@types/node-fetch` is present in both `package.json` and `package-lock.json`. I'll investigate.
