### ISSUE TITLE
ERROR: Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule'

### ISSUE THREAD

**Issue by robross0606** [apollographql/federation#904]
Receiving the following error when upgrading to v0.27.0:
```
  Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule' from 'node_modules/@apollo/federation/dist/composition/validate/preNormalization/tagDirective.js'

    Require stack:
      node_modules/@apollo/federation/dist/composition/validate/preNormalization/tagDirective.js
      node_modules/@apollo/federation/dist/composition/validate/preNormalization/index.js
      node_modules/@apollo/federation/dist/composition/validate/index.js
      node_modules/@apollo/federation/dist/composition/composeAndValidate.js
      node_modules/@apollo/federation/dist/composition/index.js
      node_modules/@apollo/federation/dist/index.js
      src/graphql/index.js
```

**Comment by robross0606** [comment]
This is purely at the module `require()` level.  I have tried with both Windows and Linux.

node: v14.17.3
npm: 6.14.12

**Comment by robross0606** [comment]
This appears to also have been resolved by upgrading from `apollo-server` v2.25.2 to v3.0.2.  However, the dependencies do not declare this as a requirement and it would seems strange that a minor (non-breaking) version increment should require a major (breaking) dependency.

**Comment by glasser** [comment]
It looks like this internal "export" from graphql-js was renamed in graphql@15: https://github.com/graphql/graphql-js/pull/2448

That means that the packages in this repo claim to support (via peer deps) graphql@14 and graphql@15 but now only support graphql@15.

Apollo Server 3 only supports graphql@15, so doing that upgrade had the side effect of fixing it for you.

federation and gateway are still pre-1.0 and it would probably be reasonable to change their peer dependencies to require graphql@15, but that should certainly be a documented explicit choice rather than unintentional like in this case.

cc @trevor-scheer

**Comment by trevor-scheer** [comment]
My initial reaction was to fix this in a backwards compatible way via some `require` / fallback logic, but [it looks like we've introduced at least one other GraphQL-15-only ism](https://github.com/apollographql/federation/blob/e250c3427a6cbf27bdae4b38faf4b14431aa562d/query-planner-js/src/composedSchema/removeInaccessibleElements.ts#L61) so my inclination is to just require v15+ in the peer dependencies rather than try to disentangle the recent work which depends on v15.

**Comment by robross0606** [comment]
> just require v15+ in the peer dependencies

My only issue there is that this no longer feels like a minor point release.

**Comment by trevor-scheer** [comment]
You're not wrong about this being a breaking change, however semver pre-1.0 doesn't follow this convention.
https://semver.org/#spec-item-4
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

We do tend to stick to not breaking anything in patch releases, but we do not consider this to be 1.0 yet and as such, the minor captures both breaking changes as well as new behavior.

I apologize for any inconvenience this causes.

**Comment by robross0606** [comment]
Okay, fair enough.

**Comment by trevor-scheer** [comment]
It's worth mentioning that npm respects this pre-1.0 convention as well and treats minors as majors. For example, the constraint `^0.27.0` will prevent `npm update` from taking you to `0.28.0+`. Hope this helps!
